In [23]:
import pandas as pd
import numpy as np

In [3]:
aerobic_df = pd.DataFrame()
people = []
for i in range(1, 10):
    people.append(f'f0{i}')
for i in range(10, 19):
    people.append(f'f{i}')
print(people)

['S01', 'S02', 'S03', 'S04', 'S05', 'S06', 'S07', 'S08', 'S09', 'S10', 'S11', 'S12', 'S13', 'S14', 'S15', 'S16', 'S17', 'S18']

In [55]:
def find_stats(stat):
    # find max number of columns needed for output df
    max_cols = 0
    for person in people:
        sample_df = pd.read_csv(f'Wearable_Dataset/STRESS/{person}/{stat}.csv')
        if sample_df.shape[0] > max_cols:
            max_cols = sample_df.shape[0]
    # make df from dictionary
    output_dict = {}
    for person in people:
        # find data for that person
        values = pd.read_csv(f'Wearable_Dataset/STRESS/{person}/{stat}.csv').iloc[:, 0].tolist()
        values = values[1:] # cut off the hertz rate
        if len(values) < max_cols:
            values += [np.nan for i in range(max_cols - len(values))] # fill with missing values
        output_dict[person] = np.array(values)
    
    output = pd.DataFrame(output_dict).T
    return output

In [57]:
aerobic_heartrate_df = find_stats('HR')
aerobic_heartrate_df

,0,1,2,3,4,5,6,7,8,9,...,3069,3070,3071,3072,3073,3074,3075,3076,3077,3078
S01,59.0,79.5,108.67,101.25,94.8,90.33,86.86,86.12,85.78,85.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
S02,94.0,73.0,104.00,91.50,109.6,121.67,130.43,136.62,141.44,145.3,...,87.6,87.63,87.7,87.75,87.82,87.87,87.95,88.02,88.08,NaN
S03,70.0,97.0,89.67,86.25,90.8,98.00,103.57,108.00,111.44,114.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
S04,85.0,73.0,65.00,63.75,70.6,75.17,78.43,81.00,83.00,84.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
S05,76.0,76.0,70.00,67.75,93.4,106.83,116.71,125.00,131.33,133.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
S06,68.0,60.0,76.33,71.75,79.2,84.17,88.00,90.25,92.22,93.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
S07,51.0,103.0,120.00,128.00,132.6,131.00,129.86,128.75,127.78,127.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
S08,49.0,54.0,59.33,58.25,60.6,66.83,71.29,74.12,76.22,77.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
S09,59.0,59.5,56.00,56.50,56.8,60.50,63.00,64.00,64.89,65.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
S10,83.0,83.0,113.33,105.75,99.2,96.50,94.57,93.25,92.22,91.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
S11,67.0,67.5,67.67,68.00,68.8,70.00,71.00,71.75,72.33,72.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
S12,60.0,60.5,68.67,66.50,65.2,64.50,64.00,64.88,65.67,66.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
S13,52.0,67.5,66.33,70.50,78.2,83.33,86.00,88.00,89.78,91.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
S14,49.0,49.0,49.00,51.50,51.0,57.17,61.43,64.50,67.00,69.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
S15,67.0,62.5,61.67,65.25,62.4,66.33,69.14,71.25,73.22,74.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
S16,85.0,85.0,107.67,99.75,91.6,90.50,89.14,87.75,86.67,85.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
S17,83.0,83.0,75.00,71.00,68.6,70.33,71.57,72.38,72.89,73.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
S18,55.0,56.5,66.00,76.75,73.4,69.33,66.71,65.00,63.78,62.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN